/****** Object:  Database [Hackmcr2018]    Script Date: 30/10/2018 09:46:12 ******/
CREATE DATABASE [Hackmcr2018]  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 2 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [Hackmcr2018] SET COMPATIBILITY_LEVEL = 140
GO

ALTER DATABASE [Hackmcr2018] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hackmcr2018] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hackmcr2018] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hackmcr2018] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hackmcr2018] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hackmcr2018] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hackmcr2018] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hackmcr2018] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hackmcr2018] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hackmcr2018] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hackmcr2018] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hackmcr2018] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hackmcr2018] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hackmcr2018] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hackmcr2018] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [Hackmcr2018] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hackmcr2018] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Hackmcr2018] SET  MULTI_USER 
GO

ALTER DATABASE [Hackmcr2018] SET ENCRYPTION ON
GO

ALTER DATABASE [Hackmcr2018] SET QUERY_STORE = ON
GO

ALTER DATABASE [Hackmcr2018] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

ALTER DATABASE [Hackmcr2018] SET  READ_WRITE 
GO


